---
- name: restart mariadb
  systemd:
    name: mariadb
    state: restarted

- name: restart entitybase
  systemd:
    name: entitybase
    state: restarted

- name: entitybase daemon reload
  systemd:
    daemon_reload: yes
