---
- name: restart alloy
  systemd:
    name: alloy
    state: restarted

- name: restart mysqld_exporter
  systemd:
    name: prometheus-mysqld-exporter
    state: restarted

- name: restart prometheus
  systemd:
    name: prometheus
    state: restarted

- name: restart loki
  systemd:
    name: loki
    state: restarted

- name: restart grafana
  systemd:
    name: grafana-server
    state: restarted
