[mariadb]
entitybase-mariadb ansible_host=54.37.4.122 node_ip=10.0.0.82

[backend]
entitybase-backend-1 ansible_host=54.37.3.57 node_ip=10.0.0.90
entitybase-backend-2 ansible_host=54.37.0.86 node_ip=10.0.0.7
entitybase-backend-3 ansible_host=54.37.6.83 node_ip=10.0.0.165
entitybase-backend-4 ansible_host=54.37.2.52 node_ip=10.0.0.173

[import]
entitybase-import ansible_host=54.37.6.32 node_ip=10.0.0.10

[entitybase:children]
backend

[all:vars]
ansible_user=ubuntu
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args=-o StrictHostKeyChecking=accept-new
entitybase_repo=https://github.com/Entitybasedev/entitybase-orchestrator.git
entitybase_branch=main
entitybase_mariadb_host=10.0.0.82
entitybase_lb_host=54.37.4.70
observability_loki_host=10.0.0.10
