---
- name: EntityBase Test Infrastructure
  hosts: all
  become: true
  roles:
    - role: common
      tags: [common]

- name: MariaDB Setup
  hosts: mariadb
  become: true
  roles:
    - role: entitybase
      tags: [mariadb]

- name: EntityBase Backends
  hosts: backend
  become: true
  roles:
    - role: entitybase
      tags: [entitybase]

- name: Import Host Setup
  hosts: import
  become: true
  roles:
    - role: entitybase
      tags: [import]

- name: Wikidata
  hosts: import
  become: true
  roles:
    - role: wikidata
      tags: [wikidata]

- name: Dashboard
  hosts: import
  become: true
  roles:
    - role: dashboard
      tags: [dashboard]

- name: Benchmark
  hosts: backend
  become: true
  roles:
    - role: benchmark
      tags: [benchmark]
